[package]
name = "DearDiray"
version = "0.1.0"
authors = ["Isala Piyarisi <code@isala.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
